language: python

install:
  - "pip install --pre -r requirements.txt"
  - "pip install python-coveralls"
  - "pip install ./yeti"

python:
  - "3.4"
  - "3.2"

script:
  - py.test --cov yeti/yeti/ yeti/tests/

after_success:
  - coveralls
