language: python

install:
  - "pip install --pre -r test-requirements.txt"
  - "pip install python-coveralls"

python:
  - "3.4"
  - "3.2"

script:
  - yeti/tests/run_tests.sh

after_success:
  - coveralls
